version: '3.1'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    container_name: golang_db
    ports:
      - "3306:3306"
    tty: true

  app:
    build:
      context: .
    volumes:
      - ".:/go"
    container_name: golang_app
    ports:
      - "8080:8080"
    tty: true
    depends_on:
      - db