version: '3.1'

services:
  mysqldb:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    container_name: mysql_db
    ports:
      - "3306:3306"
    tty: true


  adminer:
    image: adminer
    ports:
      - 8082:8080
  app:
    build:
      context: .
    volumes:
      - ".:/go"
    container_name: golang_app
    environment:
      - MYSQL_IP:mysqldb
    ports:
      - "8080:8080"
    tty: true
    depends_on:
      - mysqldb
